spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/universitysystem
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

server:
  port: 8080

jwt:
  secret: txnNK3BYhpMoesb+/P4Zq+KchlwcUpD8c2cEgxsguCA=
  expiration: 3600000

logging:
  level:
    root: INFO